# root access
sudo: required
# we need docker
services:
    - docker
# before the test run
before_install:
    - docker build -t paulocmguerreiro/docker-react -f Dockerfile.dev .

# RUN THE TEST
script:
    - docker run -e CI=true paulocmguerreiro/docker-react npm run test

# DEPLOY (aws)
#deploy:
#    edge: true
#    provider: elasticbeanstalk
#    region: "us-west-2"
#    app: "docker-react"
#    env: "Docker-env"
#    bucket_name: "elasticbeanstalk........."
#    bucket_path: "docker-react"
#    # só faz o deploy quando as alteraçoes chegarem ao master
#    on: 
#        branch: master
#        # Chaves defininas no ambientes (no próprio travis)
#        access_ley_id: $(AWS_ACCESS_KEY)
#        secret_access_key:
#            secure: "$(AWS_SECRET_KEY)"""