# RUN: docker-compose up --build

version: '3'
services: 
    # MAIN APP
    web:
        tty: true
        stdin_open: true
        restart: always
        build:
            context: .
            dockerfile: Dockerfile.dev
        ports: 
            - "3000:3000"
        volumes: 
            - /app/node_modules
            - .:/app

    # TEST APP
    tests:
        tty: true
        stdin_open: true
        build:
            context: .
            dockerfile: Dockerfile.dev
        # Não vamos aceder ao contentor
        #ports: 
        #    - "3000:3000"
        volumes: 
            - /app/node_modules
            - .:/app
        command: ["npm", "run", "test"]